# Generated by Django 4.0.4 on 2022-04-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Qalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_collage_school', models.CharField(blank=True, max_length=15, null=True)),
                ('Year_passing', models.DateField()),
                ('percentage', models.FloatField()),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qalification', to='core.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_brith', models.DateField()),
                ('bloodgroup', models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonalDetails', to='core.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='PastJobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=19, null=True)),
                ('job_role', models.CharField(blank=True, max_length=19, null=True)),
                ('year_of_work_experience', models.CharField(blank=True, max_length=19, null=True)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PastJobExperience', to='core.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=16, null=True)),
                ('ifcs', models.CharField(blank=True, max_length=6, null=True)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='core.aadhar')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='aadhar',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.aadhar'),
            preserve_default=False,
        ),
    ]
