# Generated by Django 4.0.4 on 2022-05-01 05:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aadhar_remove_address_user_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
