# Generated by Django 4.0.4 on 2022-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personaldetails_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
